  


/*
 * Created on Fri Jun 22 20:03:23 IDT 2007
 *
 * Generated by GEMS 
 */
 
package lost.tok.DiscussionViewer;



public interface EMFModelObject {
	public lost.tok.DiscussionViewer.emf.ModelObject getEMFObject();
}