/*******************************************************************************
* Copyright (c) 2005 Jules White. All rights reserved.
* This program and the accompanying materials are made available under the
* terms of the Common Public License v1.0 which accompanies this distribution,
* and is available at http://www.eclipse.org/legal/cpl-v10.html
* 
* Contributors: Jules White - initial API and implementation
******************************************************************************/


/*
 * Created on Fri Jun 22 20:03:23 IDT 2007
 *
 * Generated by GEMS 
 */
 
package lost.tok.DiscussionViewer;


import org.gems.designer.model.Atom;
import org.gems.designer.model.Model;
import org.gems.designer.model.Visitor;

/**
 * 
 */
 
public interface DiscussionViewerVisitor extends Visitor{
    public static final String MODEL_ID = "lost.tok.discussionViewer";
    
	
	


	   public void visitAbstractDicObject(AbstractDicObject tovisit);
	 
	   public void visitOpinion(Opinion tovisit);
	 
	   public void visitQuote(Quote tovisit);
	 
	   public void visitDiscussionViewer(DiscussionViewer tovisit);
	 
}

