

/*
 * Created on Fri Jun 22 20:03:23 IDT 2007
 *
 * Generated by GEMS 
 */
 
package lost.tok.DiscussionViewer;

import org.gems.designer.Memento;

public class MementoImpl implements Memento {

	private lost.tok.DiscussionViewer.emf.Memento model_;
	
	public MementoImpl(){		
	}
	
	public MementoImpl(lost.tok.DiscussionViewer.emf.Memento model){
		model_ = model;
	}
	
	public lost.tok.DiscussionViewer.emf.Memento getModel(){
		if(model_ == null){
			model_ = lost.tok.DiscussionViewer.emf.impl.DiscussionViewerFactoryImpl.eINSTANCE.createMemento();
		}
		return model_;
	}
	public void setId(String id){
		getModel().setId(id);
	}
	
	public String getId(){
		return getModel().getId();
	}
	
	public void setValue(String name, String value){
		lost.tok.DiscussionViewer.emf.MementoValue mv = lost.tok.DiscussionViewer.emf.impl.DiscussionViewerFactoryImpl.eINSTANCE.createMementoValue();
		mv.setName(name);
		mv.setValue(value);
		getModel().getData().add(mv);
	}
	public String getValue(String name){
		for(Object curr : getModel().getData()){
			lost.tok.DiscussionViewer.emf.MementoValue mv = (lost.tok.DiscussionViewer.emf.MementoValue)curr;
			if(mv.getName().equals(name)){
				return mv.getValue();
			}
		}
		return null;
	}
    
}

