

/*
 * Created on Fri Jun 22 20:03:23 IDT 2007
 *
 * Generated by GEMS 
 */
 
package lost.tok.DiscussionViewer;


/*******************************************************************************
* Copyright (c) 2005 Jules White. All rights reserved.
* This program and the accompanying materials are made available under the
* terms of the Common Public License v1.0 which accompanies this distribution,
* and is available at http://www.eclipse.org/legal/cpl-v10.html
* 
* Contributors: Jules White - initial API and implementation
******************************************************************************/

import org.gems.designer.metamodel.gen.AttributeInfo;
import org.gems.designer.model.AttributeValidator;
import org.gems.designer.ModelProvider;
import org.gems.designer.ModelRepository;
import org.gems.designer.model.Visitor;
import org.gems.designer.model.ConnectionType;
import org.gems.designer.model.Wire;
import org.eclipse.ui.views.properties.IPropertyDescriptor;

import java.util.Vector;
import org.gems.designer.model.LogicElement;
import java.util.List;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.draw2d.geometry.Point;
import org.gems.designer.model.ModelUtilities;
import org.eclipse.emf.ecore.EObject;
import lost.tok.DiscussionViewer.emf.*;

public class Opinion extends AbstractDicObject  implements Adapter, EMFModelObject, org.gems.designer.model.EMFModelElement{

	private lost.tok.DiscussionViewer.emf.Opinion model_;
	private Notifier target_;
	
	public Opinion(){		
	}
	
	public Opinion(lost.tok.DiscussionViewer.emf.Opinion model){
		model_ = model;
		super.setName(model_.getName());
		super.setID(model_.getId());
    	model_.eAdapters().add(this);
	}
	
	public lost.tok.DiscussionViewer.emf.Opinion getModel(){
		if(model_ == null){
			model_ = lost.tok.DiscussionViewer.emf.impl.DiscussionViewerFactoryImpl.eINSTANCE.createOpinion();
			super.setName(model_.getName());
			model_.eAdapters().add(this);
		}
		return model_;
	}
	
	public lost.tok.DiscussionViewer.emf.Opinion getExtendedModel(){
		return getModel();
	}
	
	public lost.tok.DiscussionViewer.emf.Opinion getEMFObject(){
		return getModel();
	}
	
    	
    	public Notifier getTarget() {
    		return target_;
    	}
    	
    	public void setTarget(Notifier newTarget) {
    		target_ = newTarget;
    	}
    	
    	public boolean isAdapterForType(Object type) {
    		return getModel() == type;
    	}
    
    
    

    public static final IPropertyDescriptor[] OPINION_ATTRIBUTE_DESCRIPTORS =
    {
    };
    public static final Object[] OPINION_DEFAULT_ATTRIBUTE_VALUES = {
       
    };
    
      	 

    
    protected void getPropertyDescriptors(Vector desc){
    	desc.addAll(java.util.Arrays.asList(OPINION_ATTRIBUTE_DESCRIPTORS));
    	super.getPropertyDescriptors(desc);
    }
    
   
    	
    public String findAttributeType(String attr){
      return super.findAttributeType(attr);
    }
    public Object getAttribute(String attr){
    	
     return super.getAttribute(attr);
   }
  
   
    public void setAttribute(String attr, Object val){
         if(attr != null){
           AttributeValidator validator = AttributeValidators.getInstance().getValidator(attr);
           if(validator != null &&
              !validator.validValue(this,attr,val)){
                return;
              }
         }	
         if(attr.equals(org.gems.designer.model.Atom.NAME)){
        	 getModel().setName((String)val);
         }   													
        super.setAttribute(attr,val);
   }
   
   public void notifyChanged(Notification notification) {
   		int type = notification.getEventType();
   		int featureId = notification.getFeatureID(DiscussionViewerPackage.class);
    		
   		switch(type) {
   		case Notification.SET:
   		
   		case Notification.ADD:
   		case Notification.REMOVE:
   		}
   }
    

	
	public List<Quote> getOneOpinion(){
		return (List<Quote>)ModelUtilities.getConnectedTargets(this,Quote.class,ContainmentConnectionType.INSTANCE);
	}
	
	
		

@Override
public void connectOutput(Wire w) {
	
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
	
		if(type.getName().equals(ContainmentConnectionType.NAME)){
	
					getModel().getOneOpinion().add(((EMFModelObject)w.getTarget()).getEMFObject());
				
      }
	
	}
	super.connectOutput(w);
}




@Override
public void disconnectOutput(Wire w) {
	
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
		if(type.getName().equals(ContainmentConnectionType.NAME)){
		    ((lost.tok.DiscussionViewer.Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getModelInstanceID()).getRoot()).removeConnection(w);
			ContainmentConnection con = (ContainmentConnection)w.getAttribute(ContainmentConnectionType.NAME);
	
					getModel().getOneOpinion().remove(((EMFModelObject)w.getTarget()).getEMFObject());
				
    }
	
	}
	super.disconnectOutput(w);
}


public void connectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectInput(w,modifymodel);
	else
		connectInput(w);
}

public void disconnectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectInput(w,modifymodel);
	else
		disconnectInput(w);
}



public void connectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectOutput(w,modifymodel);
	else
		connectOutput(w);
}

public void disconnectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectOutput(w,modifymodel);
	else
		disconnectOutput(w);
}



    
    
    public String getConnectionRole(ConnectionType ct, boolean src){
		
	    if(ct instanceof ContainmentConnectionType && src){
	       return "oneOpinion";
	    }
	
	  return super.getConnectionRole(ct,src);
	}
	
	public List<String> getRelationshipRoles(){
    	java.util.List<String> roles = super.getRelationshipRoles();
    		
	   roles.add("oneOpinion");
	
    	return roles;
    }
	
	
	public ConnectionType getConnectionTypeForRole(String role){
		
	    if("oneOpinion".equalsIgnoreCase(role)){
	       return ContainmentConnectionType.INSTANCE;
	    }
	
	  return super.getConnectionTypeForRole(role);
	}
	
    public Object getRoleValue(String role){
		
	    if("oneOpinion".equalsIgnoreCase(role)){
	       return getOneOpinion();
	    }
	
	
	
	  return super.getRoleValue(role);
	}
	
	
    
    public boolean isAbstract(){return false;}
     
    public ModelProvider getModelProvider() {
        ModelProvider provider = super.getModelProvider();
        if(provider == null){
        	provider = new DiscussionViewerProvider();
        	ModelRepository.getInstance().registerModelProvider(provider);
        }
        return provider;
    }
    
    protected void buildContainmentNames() {
    }
    
    	public List<String> getContainmentRoles(){
    	List<String> roles = super.getContainmentRoles();
    	
    	return roles;
    }
    
    public Class getParentForRole(String role){
    	
    	return super.getParentForRole(role);
    }
    
    public String getRoleForParent(Class c){
    	
    	return super.getRoleForParent(c);
    }	
    
public void accept(Visitor visitor) {
   if(visitor instanceof DiscussionViewerVisitor)
   	((DiscussionViewerVisitor)visitor).visitOpinion(this);
   else
     super.accept(visitor);
}
   
    
    
    
    public boolean isExpanded(){
    	return getExtendedModel().isExpanded();
    }
    
    public void setExpanded(boolean ex){
    	getExtendedModel().setExpanded(ex);
    	super.setExpanded(ex);
    }
    
    public Dimension getExpandSize() {
        return new Dimension(getModel().getExpandedWidth(),getModel().getExpandedHeight());
    }
    
    public void setExpandSize(Dimension d){
    	getExtendedModel().setExpandedWidth(d.width);
    	getExtendedModel().setExpandedHeight(d.height);
    	super.setExpandSize(d);
    }
    
    public String getModelID() {
        return DiscussionViewerProvider.MODEL_ID;
    }
    

}

